spring:
  jpa:
    database: postgresql
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    baselineOnMigrate: true
    enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: bob
    password: P@$$w0rd
    driver-class-name: org.postgresql.Driver

  devtools:
    livereload:
      enabled: false

server:
  error:
    include-message: always

auth:
  header: Authorization
  token: >-
    Basic YTAzZDZjZTYtMmQxNS00MjYzLWEyNWItMTAzODFhYTY2ZTRicGFzc3dvcmQ6ZDhiOTg1MTMtMjljOC00ZWFlLWI5NjgtZWNmZGNmNzQ3MThk